name: python-intro
channels:
- conda-forge
dependencies:
- python=3.10
- numpy>=1.20.0
- cupy
- nccl
- cudnn
- scipy
- numba
- pip
- sympy
- matplotlib
- pywavelets
- jupyter
- tqdm
- imageio
- scikit-learn
- scikit-image
